### ISSUE TITLE
Great node, hope to provide int value of EUC.

### ISSUE THREAD

**Issue by Datou** [cubiq/ComfyUI_FaceAnalysis#1]
It would be more convenient if the pictures and ECU values ​​could be displayed separately.

**Comment by cubiq** [comment]
I'll export the Float values with an option to skip the image generation.

**Comment by oafx** [comment]
cubiq you're the man

**Comment by ffdown** [comment]
I've tried it this way and that, but I still don't understand what it's for. Can you describe the purpose of this node more clearly?

**Comment by Datou** [comment]
> I've tried it this way and that, but I still don't understand what it's for. Can you describe the purpose of this node more clearly?

Suppose you are providing avatar generation services. With the help of ipadapter or instantid, the diffusion model generates an avatar picture based on the user's photo. The ECU value can help you judge whether the generated face image is like the user's real face. If ECU<3 It means they are very similar.

**Comment by cubiq** [comment]
you can now export just the float value or even a CSV

![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/427614/601da63e-0e07-4f8f-821c-607e01f57c63)

**Comment by ffdown** [comment]
> > I've tried it this way and that, but I still don't understand what it's for. Can you describe the purpose of this node more clearly?
> 
> Suppose you are providing avatar generation services. With the help of ipadapter or instantid, the diffusion model generates an avatar picture based on the user's photo. The ECU value can help you judge whether the generated face image is like the user's real face. If ECU<3 It means they are very similar.

If based on this analysis, adjustments could be made, it would be much more useful =)

**Comment by cubiq** [comment]
first, it's a relative analysis tool, not absolute.
second, it checks the embeds of a specific picture. you by profile and you from front are completely different embeds for the model.
check my latest video to see how to use it and why it's helpful https://www.youtube.com/watch?v=wMLiGhogOPE
