### ISSUE TITLE
Error report for filter_best

### ISSUE THREAD

**Issue by otakurlk** [cubiq/ComfyUI_FaceAnalysis#11]
When I use filter_best, the following error occurs,
thank you everyone

Error occurred when executing FaceEmbedDistance:

setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 151, in recursive_execute
output_data, output_ui = get_output_data(obj, input_data_all)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 81, in get_output_data
return_values = map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\execution.py", line 74, in map_node_over_list
results.append(getattr(obj, func)(**slice_dict(input_data_all, i)))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "F:\ComfyUI_windows_portable\ComfyUI\custom_nodes\ComfyUI_FaceAnalysis\faceanalysis.py", line 244, in analize
out = np.array(out)
^^^^^^^^^^^^^

**Comment by otakurlk** [comment]
just numpy version problem

**Comment by zejacky** [comment]
> > just numpy version problem
> 
> i'v got the same error,which version numpy to be used?

Hello
I had the same error, did the following, and now it works:

- Uninstall numpy with pip "pip uninstall numpy" (I had version 1.24.1)
- pip install numpy==1.26.4
