### ISSUE TITLE
Inhomogeneous shape error in Face Analysis node - Requesting assistance with resolving array shape inconsistency

### ISSUE THREAD

**Issue by vootox** [cubiq/ComfyUI_FaceAnalysis#15]
When processing, I get the following error message:

`!!! Exception during processing!!! setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (4,) + inhomogeneous part.`

I can provide further details if required, I would greatly appreciate any assistance in resolving this issue.

**Comment by cubiq** [comment]
I need to see the workflow and every reference images

**Comment by vootox** [comment]
The issue produces a variation of the error with different workflows so I included both.
https://github.com/cubiq/ComfyUI_FaceAnalysis/issues/8#issuecomment-2132481583

**Comment by silent37** [comment]
Hello, have you resolved this issue? I have also encountered the same problem and have upgraded the nodes and versions used to the latest version

**Comment by cubiq** [comment]
can you try to update to the latest version I pushed few minutes ago?

**Comment by vootox** [comment]
> unfortunately I cannot replicate, the provided workflows work as intended for me.
> 
> I need the full error backtrace and info about your environment (the initial comfyui message should suffice)

I didn't think it was going to be easy to replicate. The only real differences were the input images as snapshots of your video, the workflows are yours.

**Comment by vootox** [comment]
> can you try to update to the latest version I pushed few minutes ago?

Whatever you done to that new code of yours has fixed my problem, it's working! YAY!
I actually spent the last 20 hours or so studying tensor shapes with Ollama LLM chat,  learning as much as I could to try to understand that part of your code. I learnt I have much to learn!
