### ISSUE TITLE
weird blue texture when using facewarp 

### ISSUE THREAD

**Issue by abuyazid955** [cubiq/ComfyUI_FaceAnalysis#16]
https://github.com/cubiq/ComfyUI_IPAdapter_plus/issues/574

So, i have tried using basic workflow, the texture still appeared.
Here is my workflow 
[workflow (1)-issue.json](https://github.com/cubiq/ComfyUI_FaceAnalysis/files/15451425/workflow.1.-issue.json)

![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/113452309/f3f7634a-8fda-4050-b614-0de51ed8a883)

picture used : 

![82b108f2e53caeb136e5da0a24a07a18](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/113452309/7783fcfe-e996-4204-9ed6-253bdb8e23cb)

*i seek a way to solve this using vae decode and encode after facewarp nodes and before entering face bounding box nodes. this can fix the issue at the moment.

![image](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/113452309/2f5f4a6c-cf50-44d2-8716-cdc79a850fe4)

**Comment by cubiq** [comment]
seems to be a problem with insightface, I applied a patch that should solve this issue

**Comment by abuyazid955** [comment]
Thank you very much!
