### ISSUE TITLE
Node Enhancement Suggestion

### ISSUE THREAD

**Issue by PrometheusDante** [cubiq/ComfyUI_FaceAnalysis#21]
Using the `Face Embeds Distance` node as a filter to get the best rated generation out of a batch to then further process it requires two `Face Embeds Distance` nodes. One for the output image with the rating overlay and another for the one without to be passed on. 
Another output connector for the image without overlay would be a much appreciated convenience. Obsoleting the `generate_image_overlay` setting in the bottom as well. 

A little _illustration_ of the powerful effects this simple and subtle yet stylish aesthetic change would have.
Just look at this horrendous workaround, the space it takes and how messy it is!
![face_embeds_distance_node_UNsleek_UNsmooth](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/101045677/02077d8e-835a-494c-908d-46a6e735812b)
**_0/10_**. _...Who would even want to use a workflow like that? **That's right!** No one! Not a single one! 100% of all people asked shared this exact sentiment! Downright outrageous **:'(**_

**Buuuut, you sir, can make a difference! Yes, you and only you could make this beautiful, visually pleasing pipe-dream of good taste and thoughtful UI-engineering come true!**
![face_embeds_distance_node_sleek_smooth](https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/101045677/53a6ed9a-3283-4d45-86b3-f829dfde728f)
**_So simple! So sleek! So smooth!_** 

Thank you for your time and amazing efforts!

**Comment by cubiq** [comment]
Image overlay takes more than a few milliseconds, especially for large batches it adds up and it is computationally expensive. That's why it's optional

**Comment by PrometheusDante** [comment]
I didn't know that. Could the overlay switch operate automatically by checking whether or not there is anything connected to the additional image output "eval_IMAGE"?

**Comment by cubiq** [comment]
not by default, no. There might be a hack to do that but it would be client side and comfy needs to work both client and server side

**Comment by andupotorac** [comment]
@PrometheusDante Doesn't it help that you already have the metadata for the image, and can just regenerate it without the watermark?

**Comment by PrometheusDante** [comment]
@andupotorac That workflow required one with overlay and one without during the same run, but that was a while ago and I can not even say if it still looks like that. I just forgot to close this issue apparently. Really not an issue anymore, but thanks
