### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by pontius911** [cubiq/ComfyUI_FaceAnalysis#25]
Hi, I keep getting an error "TypeError: 'NoneType' object is not subscriptable" when I try to run face embed distance on the nightly version of ComfyUI. The stable version works fine, but I wanted to know if you could do something to help me fix this error. BTW: I need it to work on nightly because of WD14 tagger. It stopped working on my stable version. (doesn't like my CUDA for some reason)
[Loading 1 new model.txt](https://github.com/user-attachments/files/15759153/Loading.1.new.model.txt)

the log in txt file

**Comment by cubiq** [comment]
it seems to be a problem with the overlay, if you disable it, it should work. You can check the actual values from the console. not ideal but it's something to unlock your workflow

**Comment by pontius911** [comment]
thanks. It works... No distance or value, but it's fine.
