### ISSUE TITLE
error   ERROR: Failed building wheel for dlib

### ISSUE THREAD

**Issue by klsong505** [cubiq/ComfyUI_FaceAnalysis#31]
nentations->insightface->-r c: ai\comfyuI-aki-v1.3\ComfyuI-aki-v1.3\custom nodesicomfyuI FaceAnalysis\requirements.txt (line 3))(4.8.0)3uilding wheels for collected packages: dlib
Building wheel for dlib(pyproject.toml)error:subprocess-exited-with-error:Building wheel for dlib(pyproject.toml)did not run successfully.exit code: 1>See above for outputa subprocess, and is likely not a problem with pipnote:This error originates from
![Snipaste_2024-07-24_03-14-23](https://github.com/user-attachments/assets/eb3092f9-a34e-4804-bc43-a2e2fdebe324)
Could not build wheels for dlib, which is required to install pyproject.toml-based projects
![Snipaste_2024-07-24_03-14-23](https://github.com/user-attachments/assets/00ee9127-bed8-4bf2-b645-6113162c435f)

**Comment by klsong505** [comment]
![image](https://github.com/user-attachments/assets/bfb8aff5-5edc-4622-860b-b544f010ddc7)

**Comment by Autantpourmoi** [comment]
> try to install the pre-compiled wheel, it's linked in the readme

and for Fedora ? as i'm facing the same problem cmake already installed in .venv `Collecting dlib
  Using cached dlib-19.24.4.tar.gz (3.3 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Building wheels for collected packages: dlib
  Building wheel for dlib (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for dlib (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [26 lines of output]
      <string>:210: SyntaxWarning: invalid escape sequence '\('
      <string>:211: SyntaxWarning: invalid escape sequence '\('
      <string>:212: SyntaxWarning: invalid escape sequence '\('
      <string>:192: SetuptoolsDeprecationWarning: The test command is disabled and references to it are deprecated.
      !!
      
              ********************************************************************************
              Please remove any references to `setuptools.command.test` in all supported versions of the affected package.
      
              By 2024-Nov-15, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.
              ********************************************************************************
      
      !!
      /tmp/pip-build-env-a2inih7h/overlay/lib/python3.12/site-packages/setuptools/_distutils/dist.py:268: UserWarning: Unknown distribution option: 'tests_require'
        warnings.warn(msg)
      running bdist_wheel
      running build
      running build_ext
      Traceback (most recent call last):
        File "/home/luc/ComfyUI/.venv/bin/cmake", line 5, in <module>
          from cmake import cmake
      ModuleNotFoundError: No module named 'cmake'
      
      ERROR: CMake must be installed to build dlib
      
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for dlib
Failed to build dlib
ERROR: ERROR: Failed to build installable wheels for some pyproject.toml based projects (dlib)
(.venv) luc@fedora39:~$ 

`

**Comment by cubiq** [comment]
uninstall cmake and try again

**Comment by Autantpourmoi** [comment]
tried that 20 times , it did work on one of my previous installation but not this time.uninstalling cmake then reinstalling it doesn't change anaything it's like it couldn't find it as it is present in pip list

**Comment by cubiq** [comment]
do NOT reinstall it. just uninstall cmake and then install dlib
