### ISSUE TITLE
Why the euc and cos scores are so different using dlib or insightface?

### ISSUE THREAD

**Issue by deepfree2023** [cubiq/ComfyUI_FaceAnalysis#5]
The scores obtained by insightface are much larger than the ones from dlib. Could this be fixed?

Dib:
<img width="1550" alt="dlib" src="https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/158825912/e3123921-86d7-4719-9ce7-d6f5fcf21aad">

Insightface:
<img width="1549" alt="insightface" src="https://github.com/cubiq/ComfyUI_FaceAnalysis/assets/158825912/f8b5a59f-4466-4070-ac36-24de7941e7f9">

**Comment by cubiq** [comment]
it's not an error, the scores are not absolute but relative to the model. We could do normalization I guess not sure what is the right strategy for that

**Comment by deepfree2023** [comment]
I see. Is it true that different thresholds are required for different face analysis models?

**Comment by cubiq** [comment]
yes. that is true. I will add deepface next and see if there's a way to normalize the results
