### ISSUE TITLE
[Feature Request] Adding a "Similarity percentage"

### ISSUE THREAD

**Issue by LukeG89** [cubiq/ComfyUI_FaceAnalysis#7]
Hi @cubiq,
I just wonder, would it be possible to add a "_similarity percentage_" value to the node?

_Euclidean_ and _Cosine_ are not really intuitive, because you have to remember each time the meaning of those numbers, and it's not easy if you don't use the node on a daily basis (like you did when testing Checkpoints and FaceIDs 😵)

Is it possible to convert them into a percentage to have a more user-friendly value?
Maybe by only converting one of EUC or COS, or averaging and converting both together... I don't know, you are the expert!

Obviously it would be as relative as EUC and COS, but easier to understand (and maybe with averaging would be more accurate?)

I don't know, what do you think?

**Comment by cubiq** [comment]
the best course of action is to merge like 3 images of the person and compare them to a 4th image of the same person. That number will be your baseline. Then you use the initial 3 images to make your image generation.

I'll see if I can make this easier in the future.

**Comment by LukeG89** [comment]
Yes, but that would make the usage even harder! 😆

And it is hard to make a baseline when you are creating a custom character from scratch: for example, when you create a single face image and use it with FaceID and/or InstantID to generate images.

However, the point of a percentage is only to have a more intuitive evaluation system to rely on. Users can still check EUC and COS if they want, but for most people like me (in my opinion) a percentage would be good enough.

For example, I saw this custom node that uses dlib and a percentage: https://github.com/chflame163/ComfyUI_FaceSimilarity
